# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  fixedwidthtodelimited-benchmarks:
    dependencies:
    - base
    - fixedwidthtodelimited
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: fixedwidthtodelimited is a new Haskeleton package.
executables:
  fixedwidthtodelimited:
    dependencies:
    - base
    - fixedwidthtodelimited
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/fixedwidthtodelimited
library:
  dependencies:
  - base
  - bytestring
  - pipes
  - pipes-bytestring
  - pipes-text
  - pipes-group
  - lens-family-core
  - foldl
  - text

  source-dirs: library
license: MIT
maintainer: Author name here
name: fixedwidthtodelimited
synopsis: A new Haskeleton package.
tests:
  fixedwidthtodelimited-test-suite:
    dependencies:
    - base
    - fixedwidthtodelimited
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
